#! /bin/sh

sxhkd &

$HOME/.config/polybar/launch.sh

urxvt &

bspc monitor -d term ff

bspc config border_width	1
bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors
. "${HOME}/.cache/wal/colors.sh"

# set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color2"
bspc config presel_border_color "$color1"

compton -b
