# Shell variables
# Generated by 'wal'
wallpaper='wallpapers/lily-wine.jpg'

# Special
background='#020102'
foreground='#FCF0DC'
cursor='#FCF0DC'

# Colors
color0='#020102'
color1='#A15E56'
color2='#EA5D65'
color3='#CA8E72'
color4='#AA6290'
color5='#DEA993'
color6='#E1BFAA'
color7='#FCF0DC'
color8='#676667'
color9='#A15E56'
color10='#EA5D65'
color11='#CA8E72'
color12='#AA6290'
color13='#DEA993'
color14='#E1BFAA'
color15='#FCF0DC'
